/*
 *
 *  * Developed by - mGunawardhana
 *  * Contact email - mrgunawardhana27368@gmail.com
 *  * what's app - 071 - 9043372
 *
 */

let autoGeneratedOrderId = 1;
$('#txtOrderID').val('O-00' + autoGeneratedOrderId);

/** load all items to table */
function loadAllOderDetails() {

    /** removing table row repeating issue */
    $("#orderTblBody").empty();

    for (let oDetails of orderDetails) {
        let orderRow = `<tr>
                        <td>${oDetails.iCode}</td>
                        <td>${oDetails.itemName}</td>
                        <td>${oDetails.price}</td>
                        <td>${oDetails.Qty}</td>
                        <td>${oDetails.total}</td>
                   </tr>`;
        $('#orderTblBody').append(orderRow);
    }
}


function loadAllCustomersToCombo() {
    $('#orderCustomerID').empty();
    for (let customer of customerDetails) {
        $("#orderCustomerID").append(`<option>${customer.id}</option>`)
    }
}


/** combo operation on oder id */
$('#orderCustomerID').on('click', function () {
    let customerID = $('#orderCustomerID').val();
    for (let i = 0; i < customerDetails.length; i++) {
        if (customerDetails[i].id === customerID) {
            $("#selectCusName").val(customerDetails[i].name);
            $("#orderCustomerContact").val(customerDetails[i].address);
            $("#orderCustomerAddress").val(customerDetails[i].contact);
        }
    }
})

function loadAllItemToCombo() {
    $('#itemCodeCombo').empty();
    for (let item of itemDetails) {
        $("#itemCodeCombo").append(`<option>${item.itemCode}</option>`)
    }
}

/** combo operation on oder id */
$('#itemCodeCombo').on('click', function () {
    let itemID = $('#itemCodeCombo').val();
    for (let i = 0; i < itemDetails.length; i++) {
        if (itemDetails[i].itemCode === itemID) {
            $("#selectItemCode").val(itemDetails[i].itemCode);
            $("#txtItemDescription").val(itemDetails[i].itemName);
            $("#txtItemPrice").val(itemDetails[i].unitPrice);
            $("#txtQTYOnHand").val(itemDetails[i].qty);
        }
    }
})

$('#btnAddToTable').on('click', function () {

    let a = $("#txtItemPrice").val()
    let b = $('#txtQty').val()

    let tot = a * b;


    let orderArray = {
        iCode: $("#selectItemCode").val(),
        itemName: $("#txtItemDescription").val(),
        price: $("#txtItemPrice").val(),
        Qty: $("#txtQty").val(),
        total: tot
    }


    for (let i = 0; i < $("#orderTblBody tr").length; i++) {
        let duplicateRowDetected = false;
        /** if check duplicated row detected  ? */
        if ($("#itemCodeCombo option:selected").text() ===
            $("#orderTblBody tr").children(':nth-child(1)')[i].innerText) {

            duplicateRowDetected = true;
        }



    }

    orderDetails.push(orderArray);

    for (let i = 0; i < itemDetails.length; i++) {
        if (itemDetails[i].itemCode === $("#selectItemCode").val()) {
            itemDetails[i].qty = (itemDetails[i].qty) - ($("#txtQty").val());
        }
    }

    loadAllItems();

    /** saved notification for customer */
    savedSuccessfully();

    loadAllOderDetails();

    $('#total').val()
    $('#txtOrderID').val('O-00' + autoGeneratedOrderId);
    autoGeneratedOrderId++;
})

$('#btnSubmitOrder').on('click', function () {

    let x = $("#txtItemPrice").val()
    let y = $('#txtQty').val()

    let z = x * y;

    let singleOrder = {
        oID: $('#txtOrderID').val(),
        date: null,
        cID: $("#orderCustomerID").val(),
        iCode: $("#selectItemCode").val(),
        oQty: $("#txtQty").val(),
        Tot: z,
        discount: $("#txtDiscount").val()
    }

    purchaseDetails.push(singleOrder);

    clearTextField('#selectItemCode,#txtItemDescription,#txtItemPrice,#txtQTYOnHand');
    clearTextField('#orderCustomerID,#selectCusName,#orderCustomerContact,#orderCustomerAddress');

    savedSuccessfully();

    loadAllPurchaseDetails();
    $('#txtOrderID').val('O-00' + autoGeneratedOrderId);
    autoGeneratedOrderId++;
})