/*
 *
 *  * Developed by - mGunawardhana
 *  * Contact email - mrgunawardhana27368@gmail.com
 *  * what's app - 071 - 9043372
 *
 */

let autoGeneratedOrderId = 1;
$('#txtOrderID').val('O-00'+autoGeneratedOrderId);


function loadAllCustomersToCombo(){
    $('#orderCustomerID').empty();
    for (let customer of customerDetails) {
        $("#orderCustomerID").append(`<option>${customer.id}</option>>`)
    }
}


/** combo operation on oder id */
$('#orderCustomerID').on('click',function (){
    let customerID = $('#orderCustomerID').val();
    for (let i = 0; i < customerDetails.length; i++) {
        if (customerDetails[i].id === customerID) {
            $("#selectCusName").val(customerDetails[i].name);
            $("#orderCustomerContact").val(customerDetails[i].address);
            $("#orderCustomerAddress").val(customerDetails[i].contact);
        }
    }
})

/** combo operation on oder id */
$('#orderCustomerID').on('click',function (){
    let customerID = $('#orderCustomerID').val();
    for (let i = 0; i < itemDetails.length; i++) {
        if (customerDetails[i].id === customerID) {
            $("#selectCusName").val(customerDetails[i].name);
            $("#orderCustomerContact").val(customerDetails[i].address);
            $("#orderCustomerAddress").val(customerDetails[i].contact);
        }
    }
})

